### ISSUE TITLE
Add Fabric version and update the support version to 1.17/1.17.1/1.18/1.18.1

### ISSUE THREAD

**Issue by xiaobaimao233** [Thuts-Mods/ThutTech#30]
My friend open a server and want to add a lift mod, but the lift mod on Minecraft 1.17 and above of this version and use Fabric API is extremely few.

So, could you add Fabric version and update the support version to 1.17/1.17.1/1.18/1.18.1?
If you can't, I will find a substitute.

Thank you!

**Comment by Thutmose** [comment]
I have no plans of re-writing this mod for any not-forge modloaders, as it is not a trivial thing to do, anyone else is free to try to do such a re-write, most of the code is actually in thutcore rather than this one.

My suggestion would be to try to use forge instead, as this is already on 1.18.1 for forge.
